---
title: "PGV multiple comparison tests"
output:
  html_document:
  keep_md: yes
date: '`r format(Sys.time(), "%B %d, %Y")`'
---
### Preparing data
```{r}
setwd("C:/Users/ZhangYutong/Desktop")
gv <- read.csv("GV0_PGV2.csv")
str(gv)
```

## Power analysis

Calculate [effect size](https://en.wikipedia.org/wiki/Effect_size) using [Cohen's d](https://en.wikipedia.org/wiki/Effect_size#Cohen.27s_d).
```{r}
n1 <- length(gv$GV_0)
n2 <- length(gv$GV_1)
s <- sqrt(((n1 -1) * var(gv$GV_0) + (n2 -1) * var(gv$GV_1)) / (n1 + n2 - 2))
(Cd <- (mean(gv$GV_0) - mean(gv$GV_1)) / s)

install.packages("effsize")
library(effsize)
cohen.d(gv$GV_0, gv$GV_1)
```
*Rule of thumb*: d=0.2,small effect; d=0.5,medium effect; d=0.8 large effect.

## Tukey test
```{r}
sgv <- stack(gv)
names(sgv) <- c("Values", "Groups")
str(sgv)
```

1. Fit an ANOVA model

```{r}
sgv.aov <- aov(Values ~ Groups, data = sgv)
summary(sgv.aov)
```

2. Conduct the Tukey test

```{r}
install.packages("multcomp")
library(multcomp)
sgv.mc <- glht(sgv.aov, linfct = mcp(Groups = "Tukey"))
summary(sgv.mc)
TukeyHSD(sgv.aov)
```

3. Calculate the two-sided, 95% confindence interval and plot the interval

```{r}
sgv.ci <- confint(sgv.mc, level = 0.95)
sgv.ci
par(mfrow = c(1, 1), mar = c(4, 12, 2, 1))  
plot(sgv.ci, xlab = "Values")
```

4. Produce a compact letter display of all pair-wise comparisons

```{r}
sgv.cld <- cld(sge.mc)
par(mfrow = c(1, 1), mar = c(4, 14, 2, 1))  
plot(sgv.cld)
```
